title: DeskUp Pro Standing Desk Controller
description: by SmartHomeGuys

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io
