title: DeskUp Pro -  Standing Desk Controller (RJ12)
description: Control Maidesite, Ikea and other standing desks from your smart home system with DeskUp Pro

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: just-the-docs/just-the-docs
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
