title: DeskUp Pro - Controls a Standing Desk from your Smart Home System
description: Use a DeskUp Pro on a standing desk with an RJ12 port to automate it from a smart home system (like Home Assistant and others)

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: just-the-docs/just-the-docs
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
