title: DeskUp Pro - Standing Desk Controller
description: Making desks with an RJ12 port smart

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: just-the-docs/just-the-docs
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
