title: DeskUp Pro - Automate your Standing Desk
description: Making desks with an RJ12 port smart and automating them in a smart home system (like Home Assistant) with the DeskUp Pro

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: just-the-docs/just-the-docs
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
