substitutions:
  name: "deskup-pro-controller"
  friendly_name: "DeskUp Pro Controller"

packages:
  #device_base: !include common/standingdesk/base.yaml
  device_base:
    url: https://github.com/SmartHomeGuys/ESP32-RJ12-Standing-Desk-Controller
    files: [common/base.yaml, common/deployment-config.yaml]
    ref: main
    refresh: 1min

logger:
  level: DEBUG   #VERBOSE

update:
  - platform: http_request
    id: update_http_request
    name: Desk Firmware
    source: https://smarthomeguys.github.io/RJ12-Standing-Desk-Controller/manifest.json
    disabled_by_default: false
    update_interval: 1min

dashboard_import:
  package_import_url: github://SmartHomeGuys/ESP32-RJ12-Standing-Desk-Controller/standing-desk-controller.yaml@main
  import_full_config: false  # Adopted fine
  #import_full_config: true  # Failed to import error

