substitutions:
  name: "standing-desk-controller"
  friendly_name: "Standing Desk Controller"

packages:
  #device_base: github://SmartHomeGuys/ESP32-RJ12-Standing-Desk-Controller/common/base.yaml@main
  device_base:
    url: https://github.com/SmartHomeGuys/ESP32-RJ12-Standing-Desk-Controller
    files: [common/base.yaml]  # optional; if not specified, all files will be included
    ref: main
    refresh: 1min

logger:
  level: DEBUG   #VERBOSE

dashboard_import:
  package_import_url: github://SmartHomeGuys/ESP32-RJ12-Standing-Desk-Controller/standing-desk-controller.yaml@main
  import_full_config: false  # Adopted fine
  #import_full_config: true  # Failed to import error