substitutions:
  name: "deskup-pro"
  friendly_name: "DeskUp Pro Controller"
  #tx_pin: "GPIO13"
  #rx_pin: "GPIO12"

  #esp32_led_order: "RGB"  #GRB
  
  #Default to the physical Min and Max height limits for a 
  #Maidesite TH2 Plus Art desk which are the lowest/highest
  #height range of all Maidesite desks. 
  #But you can override these using the 2 text boxes.
  #Which should either match your desk physical min/max height limit
  #or just be set to the min/max desk height you will use.
  #The cover/slider control will then be constrained to these min/max values.
  #Desk presets and nudge buttons are not constrained to these.
  #desk_min_height: "62"
  #desk_max_height: "126"

packages:
  device_base: !include common/base.yaml

logger:
  level: DEBUG   #VERBOSE

update:
  - platform: http_request
    id: update_http_request
    name: Desk Firmware
    source: https://smarthomeguys.github.io/DeskUp-Pro-Controller-RJ12/manifest.json
    disabled_by_default: false
    update_interval: 6h #1min

dashboard_import:
  package_import_url: github://SmartHomeGuys/DeskUp-Pro-Controller-RJ12/deskup-pro-controller.yaml@main
  import_full_config: false
