#Useful guide for commands
#https://esphome.io/web-api/index.html

# Get current desk height
#GET http://192.168.71.232/sensor/Desk Height
#GET http://192.168.71.232/sensor/Desk Height Percent

# Get preset button M1,2,3,4 height value from the desk
#GET http://192.168.71.232/sensor/Desk M1 Height
#GET http://192.168.71.232/sensor/Desk M2 Height
#GET http://192.168.71.232/sensor/Desk M3 Height
#GET http://192.168.71.232/sensor/Desk M4 Height

# Get desk idle time in secconds
#GET http://192.168.71.232/sensor/Idle Time

# Get desk idle timestanp
#GET http://192.168.71.232/text_sensor/Idle Timestamp

# Get desk Status
#GET http://192.168.71.232/text_sensor/Desk Status

#GET http://192.168.71.232/sensor/ESP32 Uptime


# Move the desk to the specified height
#POST http://192.168.71.232/number/Desk Height/set?value=80 HTTP/1.1

# Get desk height
#GET http://192.168.71.232/number/Desk Height

# Press preset button M1,2,3,4 on the desk
#POST http://192.168.71.232/button/Desk M1/press
#POST http://192.168.71.232/button/Desk M2/press
#POST http://192.168.71.232/button/Desk M3/press
#POST http://192.168.71.232/button/Desk M4/press

#POST http://192.168.71.232/button/Desk Nudge Down/press
#POST http://192.168.71.232/button/Desk Nudge Up/press
#POST http://192.168.71.232/button/Desk Stop/press

# Press Memory Preset Buttons 1,2,3,4
#POST http://192.168.71.232/button/Set Desk M1/press
#POST http://192.168.71.232/button/Set Desk M2/press
#POST http://192.168.71.232/button/Set Desk M3/press
#POST http://192.168.71.232/button/Set Desk M4/press

#Restart the ESP32 device
#POST http://192.168.71.232/button/ESP32 Restart/press


# Get / Set Min & Max Heights
#GET http://192.168.71.232/number/Max Height
#GET http://192.168.71.232/number/Min Height

#POST http://192.168.71.232/number/Max Height/set?value=102
#POST http://192.168.71.232/number/Min Height/set?value=74

# Get / Set Up & Down Offset values
#GET http://192.168.71.232/number/Offset Down by
#GET http://192.168.71.232/number/Offset Up by
#POST http://192.168.71.232/number/Offset Down by/set?value=0
#POST http://192.168.71.232/number/Offset Up by/set?value=1


#Cover / Slider 
#GET http://192.168.71.232/cover/Height Slider
#POST http://192.168.71.232/cover/Height Slider/set?position=0.1


#ESP32 LED
#GET http://192.168.71.232/light/ESP32 LED
#POST http://192.168.71.232/light/ESP32 LED/turn_off

# SeeedStudio XIAO C6 chip only has a yellow LED so can only turn on/off
#POST http://192.168.71.232/light/ESP32 LED/turn_on

# S3 chip has RGB LED
#POST http://192.168.71.232/light/ESP32 LED/turn_on?r=25&g=25&b=125